
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: front-dev-karpenter-node
spec:
  subnetSelector:
    kubernetes.io/cluster/${cluster_name}: owned
  securityGroupSelector:
    kubernetes.io/cluster/${cluster_name}: owned